./srcs/cast_converter.sv
./srcs/cast_credit_counter.sv
./srcs/cast_crossbar.sv
./srcs/cast_input_controller.sv
./srcs/cast_input_stage.sv
./srcs/cast_network.sv
./srcs/cast_output_stage.sv
./srcs/cast_route_table.sv
./srcs/cast_router.sv
./srcs/cast_vc_allocator.sv
./srcs/merge_network.sv
./srcs/merge_router.sv
./srcs/mtx_arbiter.sv
./srcs/mux_data_valid_5to1.sv
./srcs/mux_ready_5to1.sv
./srcs/network_interface.sv
./srcs/network.sv
./srcs/SyncFIFO_RTL.sv
./srcs/SyncFIFO_RTL_UBM.sv
./srcs/SyncFIFO_RTL_CNT.sv

./system.sv
./top_tb.sv
./virtual_pe.sv