../srcs/mtx_arbiter.sv
../srcs/cast_credit_counter.sv
../srcs/cast_crossbar.sv
../srcs/cast_input_controller.sv
../srcs/cast_input_stage.sv
../srcs/cast_output_stage.sv
../srcs/cast_route_table.sv
../srcs/cast_router.sv
../srcs/cast_vc_allocator.sv
../srcs/mux_data_valid_5to1.sv
../srcs/mux_ready_5to1.sv
../srcs/SyncFIFO_RTL.sv
../srcs/merge_router.sv
../srcs/cast_converter.sv

./cast_network.sv
./merge_network.sv
./system.sv
./virtual_pe.sv
./top_tb.sv